server:
  port: 8001

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/o2Suppliers
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      show_sql: true
#
#hibernate:
#  dialect: org.hibernate.dialect.MySQLDialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/o2Suppliers?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect